// INFO: Variables used in the article
:local_user: user
:local_hostname: localhost

= Proxmox Virtual Environment step by step

== Download ISO installer and prepare a USB Flash Drive as Installation Medium

Download https://www.proxmox.com/en/downloads/proxmox-virtual-environment/iso/proxmox-ve-8-1-iso-installer[PVE installer] ISO file.
Use `dd` command like presented below to populate USB Flash Drive with it. The
flash drive needs to have at least 1 GB of storage available.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dd bs=1M conv=fdatasync if=./proxmox-ve_8.1-1.iso of=/dev/sda
-------------------------------------------------------------------------------

Remember to use raw block device like `/dev/sda`, `/dev/sdb`, `/dev/sdc`, ...
instead of partition block device like `/dev/sda1`, `/dev/sdb1`, `/dev/sdc1`,
... .

== Enable Vanderpool (Intel Virtualization Technology)

Enter BIOS/UEFI menu and enable the VT-d CPU flags. Because some menus are
different look for something like Enable Virtualization Technology

== Set boot priority for your UEFI-based Proxmox drive

You may see Proxmox and (UEFI) Proxmox boot options or something similar. You
may need to disable CSM to ensure the system boots using UEFI.

== Install Proxmox Virtual Environment

Use option `Install Proxmoc VE (Graphical)`. The installation process is
straightforward. One important thing is to set proper `Hostname (FQDN)`. Names
like `hostname_abc.def` will cause errors. Try to use names like
`hostname.abc`.

== Solving anoying warning problem.

When you SSH into Proxmox for very first time, an anoying warinig appears when
you type command and use `tab` for auto completion.

-------------------------------------------------------------------------------
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "pl_PL.UTF-8",
	LC_NAME = "pl_PL.UTF-8",
	LC_MONETARY = "pl_PL.UTF-8",
	LC_PAPER = "pl_PL.UTF-8",
	LC_IDENTIFICATION = "pl_PL.UTF-8",
	LC_TELEPHONE = "pl_PL.UTF-8",
	LC_MEASUREMENT = "pl_PL.UTF-8",
	LC_TIME = "pl_PL.UTF-8",
	LC_NUMERIC = "pl_PL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
-------------------------------------------------------------------------------

Proceed with steps below to resolve this issue.

Option no 1 is to use semi-graphical locales configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure locales
-------------------------------------------------------------------------------

Option no 2 is to use console locales configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
[{local_user}@{local_hostname} ~]$ sed -i -e 's/# pl_PL.UTF-8 UTF-8/pl_PL.UTF-8 UTF-8/' /etc/locale.gen
-------------------------------------------------------------------------------

Verify locales to be generated.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep -v \# /etc/locale.gen

en_US.UTF-8 UTF-8
pl_PL.UTF-8 UTF-8
-------------------------------------------------------------------------------

Generate locales.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ locale-gen
-------------------------------------------------------------------------------

== Verify time zone configuration.

Option no 1 is to use semi-graphical time zone configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure tzdata
-------------------------------------------------------------------------------

Option no 2 is to use console time zone configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ echo Europe/Warsaw > /etc/timezone
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure -f noninteractive tzdata

Current default time zone: 'Europe/Warsaw'
Local time is now:      czw, 1 lut 2024, 12:47:06 CET.
Universal Time is now:  Thu Feb  1 11:47:06 UTC 2024.

-------------------------------------------------------------------------------

== GRUB Setup

SSH into your host and edit `/etc/default/grub` file. Look for
`GRUB_CMDLINE_LINUX_DEFAULT="quiet"` line.

For Intel modify line.

-------------------------------------------------------------------------------
GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"
-------------------------------------------------------------------------------

For AMD modify line.

-------------------------------------------------------------------------------
GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt"
-------------------------------------------------------------------------------

Update the UEFI boot entries.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ update-grub2
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.5.11-4-pve
Found initrd image: /boot/initrd.img-6.5.11-4-pve
Found memtest86+ 64bit EFI image: /boot/memtest86+x64.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
-------------------------------------------------------------------------------

== Verify IOMMU is enabled

After reboot.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dmesg | grep -e "DMAR: IOMMU enabled"
-------------------------------------------------------------------------------

If there is no output, something is wrong.

== Kernel Modules

Add the following lines to `/etc/modules`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ echo vfio >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_iommu_type1 >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_pci >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_virqfd >> /etc/modules
-------------------------------------------------------------------------------

Add the kernel modules to the boot list.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ update-initramfs -u
update-initramfs: Generating /boot/initrd.img-6.5.11-4-pve
Running hook script 'zz-proxmox-boot'..
Re-executing '/etc/kernel/postinst.d/zz-proxmox-boot' in new private mount namespace..
No /etc/kernel/proxmox-boot-uuids found, skipping ESP sync.
System booted in EFI-mode but 'grub-efi-amd64' meta-package not installed!
Install 'grub-efi-amd64' to get updates.
Couldn't find EFI system partition. It is recommended to mount it to /boot or /efi.
Alternatively, use --esp-path= to specify path to mount point.
-------------------------------------------------------------------------------

== Create a new VM able to display on physical screen

New virtual machine should be created with default parameters. Only listed
below need special attention.

`System` > `Graphic card` > `Default`
`System` > `Machine` > `q35`
`System` > `BIOS` > `OVMF (UEFI)`
`Memory` > `Memory (MiB)` > `6144` (this has be less than available on host)

Options below just helps with maintenance.

`System` > `SCSI Controller` > `VirtIO SCSI` (not single)
`System` > `Qemu Agnet` > `enabled`
`System` > `Add EFI Disk` > `enabled`

Install your favorite OS on fresh VM. Launch it, configure and ensure that
default display works fine.

Click right on new VM and stop it. Go to `Hardware`, click `Add` and choose
`PCI Device`. Fill window `Edit: PCI Device` similar to presented.

`Raw Device` > `Device` > `0000:00:02.0`
`Raw Device` > `All Functions` > `enabled`
`Primary GPU` > `enabled`
`PCI-Express` > `enabled`

Your `Display` should be now configured to `none (none)`.

Start your VM and watch output on physical display.

== Play audio from VM on host via PulseAudio

=== Host server configuration without any access restrictions

First install manadatory package.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ sudo apt install pulseaudio
-------------------------------------------------------------------------------

Double check if `~/.config/pulse` directory is not existing (from previous
installation or launch for example). This setup is applied system wide so you
do not want to mess with any local setup.

Add following line to `/etc/pulse/default.pa` file. For start do not worry
about any access restrictions. For base setup each host is allowed to connect
to server and stream its own audio.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-anonymous=1
-------------------------------------------------------------------------------

Start server as *current desktop user*. In case of non-desktop users just make
sure that user belongs to proper groups if something goes wrong. It is not
recommended to launch PulseAudio daemon as root user!

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --start
-------------------------------------------------------------------------------

If there is no problems with daemon there should be no output on console. You
can always check if your server is running.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --check && echo PulseAudio server is running || echo PulseAudio server is not running"
-------------------------------------------------------------------------------

Stop your server.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --kill
-------------------------------------------------------------------------------

=== Guest client configuration for Ubuntu 23.10.1 (Mantic Minotaur)

Add proper system wide environment variable.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_SERVER /etc/environment
PULSE_SERVER=192.168.4.5
-------------------------------------------------------------------------------

You can specify protocol and port if needed for configuration other than
default.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_SERVER /etc/environment
PULSE_SERVER=tcp:192.168.4.5:4713
-------------------------------------------------------------------------------

Restart your login session or reboot.

=== Server configuration with access restriction (ACL based)

Server can restrict connections only to clients from some particular network.
To achieve that you need to modify `/etc/pulse/default.pa` file again. Your
line should restrict access by ACL rule.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.0/24
-------------------------------------------------------------------------------

Other example of ACL rule is to restrict connections only to particular address.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27
-------------------------------------------------------------------------------

You are able to list particular addresses.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27;192.168.4.28
-------------------------------------------------------------------------------

You are able to list particular networks.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.0/24;192.168.5.0/16
-------------------------------------------------------------------------------

But also you can mix them together.

-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27;192.168.5.0/16
-------------------------------------------------------------------------------

=== Server configuration with access restriction (token based)

Server can restrict connections only to clients with proper token. The token is
called `cookie`. The same `cookie` need to be located on both server and client
side to establish valid connection.

To achieve that you need to modify `/etc/pulse/default.pa` file again.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp
-------------------------------------------------------------------------------

Be sure that your server is killed properly. Start server again as
*current desktop user* (not root).

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --start
-------------------------------------------------------------------------------

Random `cookie` is generated by server in `~/.config/pulse/cookie`. Keep in
mind that in this context directory `~` means home directory of
*current desktop user* on server. The easiest way to keep the same `cookie` on
both sides is to use `scp` to copy this file from server to proper place on
client side. Default location of it is also `~/.config/pulse/cookie`. In this
context directory `~` means home directory of *desktop user on client side* who
is due to use server as audio output (audio sink). In other words user on
server side and user on client side are not the same user.

You can use environment variable `PULSE_COOKIE` set to some non-default path on
*client side*. It *does not work for server*. Presented example shows how to
configure client side to store `cookie` in `/tmp/pulseaudio.cookie` file.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_COOKIE /etc/environment
PULSE_COOKIE=/tmp/pulseaudio.cookie
-------------------------------------------------------------------------------

Such setup is useful for system wide config on client size where many users
want to use the same audio server. Keep in mind that sometimes it is easier
just to set ACL for particular address.

== Source of information

* https://pve.proxmox.com/wiki/PCI_Passthrough[Proxmox PCI Passthrough]
* https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF[PCI passthrough via OVMF]
* https://www.reddit.com/r/homelab/comments/b5xpua/the_ultimate_beginners_guide_to_gpu_passthrough[The Ultimate Beginner's Guide to GPU Passthrough]
* https://www.reddit.com/r/Proxmox/comments/lcnn5w/proxmox_pcie_passthrough_in_2_minutes[Proxmox PCI(e) Passthrough in 2 minutes]
* https://elijahliedtke.medium.com/home-lab-guides-proxmox-6-pci-e-passthrough-with-nvidia-43ccfb9424de[Home Lab Guides: Proxmox 6 — PCI(e) Passthrough with NVIDIA]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Running[Running the PulseAudio]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Network[Network Setup  of the PulseAudio]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/ServerStrings[The Format of Server Strings in the PulseAudio]
* https://wiki.archlinux.org/title/PulseAudio/Examples#Set_default_input_source[Examples of PulseAudio usage]
* https://wiki.archlinux.org/title/PulseAudio#Configuration_command[PulseAudio environment variables]
* https://gist.github.com/xarinatan/c415341ff34eab445cfb073988dcf6c1[How to set up PulseAudio over Network]]


