// INFO: Variables used in the articleS
:local_user: user
:local_hostname: localhost

= Proxmox Virtual Environment step by step

== Download ISO installer and prepare a USB Flash Drive as Installation Medium

Download https://www.proxmox.com/en/downloads/proxmox-virtual-environment/iso/proxmox-ve-8-1-iso-installer[PVE installer] ISO file.
Use `dd` command like presented below to populate USB Flash Drive with it. The
flash drive needs to have at least 1 GB of storage available.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dd bs=1M conv=fdatasync if=./proxmox-ve_8.1-1.iso of=/dev/sda
-------------------------------------------------------------------------------

Remember to use raw block device like `/dev/sda`, `/dev/sdb`, `/dev/sdc`, ...
instead of partition block device like `/dev/sda1`, `/dev/sdb1`, `/dev/sdc1`,
... .

== Enable Vanderpool (Intel Virtualization Technology)

Enter BIOS/UEFI menu and enable the VT-d CPU flags. Because some menus are
different look for something like Enable Virtualization Technology

== Set boot priority for your UEFI-based Proxmox drive

You may see Proxmox and (UEFI) Proxmox boot options or something similar. You
may need to disable CSM to ensure the system boots using UEFI.

== Install Proxmox Virtual Environment

Use option `Install Proxmoc VE (Graphical)`. The installation process is
straightforward. One important thing is to set proper `Hostname (FQDN)`. Names
like `hostname_abc.def` will cause errors. Try to use names like
`hostname.abc`.

== Solving anoying warning problem

When you SSH into Proxmox for very first time, an anoying warinig appears when
you type command and use `tab` for auto completion.

-------------------------------------------------------------------------------
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_ADDRESS = "pl_PL.UTF-8",
	LC_NAME = "pl_PL.UTF-8",
	LC_MONETARY = "pl_PL.UTF-8",
	LC_PAPER = "pl_PL.UTF-8",
	LC_IDENTIFICATION = "pl_PL.UTF-8",
	LC_TELEPHONE = "pl_PL.UTF-8",
	LC_MEASUREMENT = "pl_PL.UTF-8",
	LC_TIME = "pl_PL.UTF-8",
	LC_NUMERIC = "pl_PL.UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
-------------------------------------------------------------------------------

Proceed with steps below to resolve this issue.

Option no 1 is to use semi-graphical locales configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure locales
-------------------------------------------------------------------------------

Option no 2 is to use console locales configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
[{local_user}@{local_hostname} ~]$ sed -i -e 's/# pl_PL.UTF-8 UTF-8/pl_PL.UTF-8 UTF-8/' /etc/locale.gen
-------------------------------------------------------------------------------

Verify locales to be generated.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep -v \# /etc/locale.gen

en_US.UTF-8 UTF-8
pl_PL.UTF-8 UTF-8
-------------------------------------------------------------------------------

Generate locales.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ locale-gen
-------------------------------------------------------------------------------

== Verify time zone configuration

Option no 1 is to use semi-graphical time zone configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure tzdata
-------------------------------------------------------------------------------

Option no 2 is to use console time zone configuration.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ echo Europe/Warsaw > /etc/timezone
[{local_user}@{local_hostname} ~]$ dpkg-reconfigure -f noninteractive tzdata

Current default time zone: 'Europe/Warsaw'
Local time is now:      czw, 1 lut 2024, 12:47:06 CET.
Universal Time is now:  Thu Feb  1 11:47:06 UTC 2024.

-------------------------------------------------------------------------------

== GRUB Setup

SSH into your host and edit `/etc/default/grub` file. Look for
`GRUB_CMDLINE_LINUX_DEFAULT="quiet"` line.

For Intel modify line.

-------------------------------------------------------------------------------
GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"
-------------------------------------------------------------------------------

For AMD modify line.

-------------------------------------------------------------------------------
GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt"
-------------------------------------------------------------------------------

Update the UEFI boot entries.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ update-grub2
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-6.5.11-4-pve
Found initrd image: /boot/initrd.img-6.5.11-4-pve
Found memtest86+ 64bit EFI image: /boot/memtest86+x64.efi
Adding boot menu entry for UEFI Firmware Settings ...
done
-------------------------------------------------------------------------------

== Verify IOMMU is enabled

After reboot.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ dmesg | grep -e "DMAR: IOMMU enabled"
-------------------------------------------------------------------------------

If there is no output, something is wrong.

== Kernel Modules

Add the following lines to `/etc/modules`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ echo vfio >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_iommu_type1 >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_pci >> /etc/modules
[{local_user}@{local_hostname} ~]$ echo vfio_virqfd >> /etc/modules
-------------------------------------------------------------------------------

Add the kernel modules to the boot list.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ update-initramfs -u
update-initramfs: Generating /boot/initrd.img-6.5.11-4-pve
Running hook script 'zz-proxmox-boot'..
Re-executing '/etc/kernel/postinst.d/zz-proxmox-boot' in new private mount namespace..
No /etc/kernel/proxmox-boot-uuids found, skipping ESP sync.
System booted in EFI-mode but 'grub-efi-amd64' meta-package not installed!
Install 'grub-efi-amd64' to get updates.
Couldn't find EFI system partition. It is recommended to mount it to /boot or /efi.
Alternatively, use --esp-path= to specify path to mount point.
-------------------------------------------------------------------------------

== Create a new VM able to display on physical screen

New virtual machine should be created with default parameters. Only listed
below need special attention.

`System` > `Graphic card` > `Default`
`System` > `Machine` > `q35`
`System` > `BIOS` > `OVMF (UEFI)`
`Memory` > `Memory (MiB)` > `6144` (this has be less than available on host)

Options below just helps with maintenance.

`System` > `SCSI Controller` > `VirtIO SCSI` (not single)
`System` > `Qemu Agnet` > `enabled`
`System` > `Add EFI Disk` > `enabled`

Install your favorite OS on fresh VM. Launch it, configure and ensure that
default display works fine.

Click right on new VM and stop it. Go to `Hardware`, click `Add` and choose
`PCI Device`. Fill window `Edit: PCI Device` similar to presented.

`Raw Device` > `Device` > `0000:00:02.0`
`Raw Device` > `All Functions` > `enabled`
`Primary GPU` > `enabled`
`PCI-Express` > `enabled`

Your `Display` should be now configured to `none (none)`.

Start your VM and watch output on physical display.

== Play audio from VM on host via PulseAudio

=== Host server configuration without any access restrictions

First install manadatory package.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ sudo apt install pulseaudio
-------------------------------------------------------------------------------

Double check if `~/.config/pulse` directory is not existing (from previous
installation or launch for example). This setup is applied system wide so you
do not want to mess with any local setup.

Add following line to `/etc/pulse/default.pa` file. For start do not worry
about any access restrictions. For base setup each host is allowed to connect
to server and stream its own audio.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-anonymous=1
-------------------------------------------------------------------------------

Start server as *current desktop user*. In case of non-desktop users just make
sure that user belongs to proper groups if something goes wrong. It is not
recommended to launch PulseAudio daemon as root user!

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --start
-------------------------------------------------------------------------------

If there is no problems with daemon there should be no output on console. You
can always check if your server is running.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --check && echo PulseAudio server is running || echo PulseAudio server is not running"
-------------------------------------------------------------------------------

Stop your server.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --kill
-------------------------------------------------------------------------------

=== Guest client configuration for Ubuntu 23.10.1 (Mantic Minotaur)

Add proper system wide environment variable.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_SERVER /etc/environment
PULSE_SERVER=192.168.4.5
-------------------------------------------------------------------------------

You can specify protocol and port if needed for configuration other than
default.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_SERVER /etc/environment
PULSE_SERVER=tcp:192.168.4.5:4713
-------------------------------------------------------------------------------

Restart your login session or reboot.

=== Server configuration with access restriction (ACL based)

Server can restrict connections only to clients from some particular network.
To achieve that you need to modify `/etc/pulse/default.pa` file again. Your
line should restrict access by ACL rule.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.0/24
-------------------------------------------------------------------------------

Other example of ACL rule is to restrict connections only to particular address.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27
-------------------------------------------------------------------------------

You are able to list particular addresses.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27;192.168.4.28
-------------------------------------------------------------------------------

You are able to list particular networks.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.0/24;192.168.5.0/16
-------------------------------------------------------------------------------

But also you can mix them together.

-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp auth-ip-acl=192.168.4.27;192.168.5.0/16
-------------------------------------------------------------------------------

=== Server configuration with access restriction (token based)

Server can restrict connections only to clients with proper token. The token is
called `cookie`. The same `cookie` need to be located on both server and client
side to establish valid connection.

To achieve that you need to modify `/etc/pulse/default.pa` file again.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ tail -n 1 /etc/pulse/default.pa
load-module module-native-protocol-tcp
-------------------------------------------------------------------------------

Be sure that your server is killed properly. Start server again as
*current desktop user* (not root).

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ pulseaudio --start
-------------------------------------------------------------------------------

Random `cookie` is generated by server in `~/.config/pulse/cookie`. Keep in
mind that in this context directory `~` means home directory of
*current desktop user* on server. The easiest way to keep the same `cookie` on
both sides is to use `scp` to copy this file from server to proper place on
client side. Default location of it is also `~/.config/pulse/cookie`. In this
context directory `~` means home directory of *desktop user on client side* who
is due to use server as audio output (audio sink). In other words user on
server side and user on client side are not the same user.

You can use environment variable `PULSE_COOKIE` set to some non-default path on
*client side*. It *does not work for server*. Presented example shows how to
configure client side to store `cookie` in `/tmp/pulseaudio.cookie` file.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep PULSE_COOKIE /etc/environment
PULSE_COOKIE=/tmp/pulseaudio.cookie
-------------------------------------------------------------------------------

Such setup is useful for system wide config on client size where many users
want to use the same audio server. Keep in mind that sometimes it is easier
just to set ACL for particular address.

=== Launching server with systemd as desktop user

Server can be launched with `systemd`. There are examples available how to
launch PulseAudio properly. Keep in mind that launching PulseAudio as
*root is not recommended*. You should launch daemon as standard *desktop user*.

Copy examples to systemd directories, which are dedicated for admin scripts.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cp /usr/lib/systemd/user/pulseaudio.socket /etc/systemd/system/pulseaudio.socket
[{local_user}@{local_hostname} ~]$ cp /usr/lib/systemd/user/pulseaudio.service /etc/systemd/system/pulseaudio.service
-------------------------------------------------------------------------------

Read information from `pulseaudio.service` presented.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ grep \# /etc/systemd/system/pulseaudio.service 
# We require pulseaudio.socket to be active before starting the daemon, because
# while it is possible to use the service without the socket, it is not clear
# why it would be desirable.
#
# A user installing pulseaudio and doing `systemctl --user start pulseaudio`
# will not get the socket started, which might be confusing and problematic if
# the server is to be restarted later on, as the client autospawn feature
# might kick in. Also, a start of the socket unit will fail, adding to the
# confusion.
#
# After=pulseaudio.socket is not needed, as it is already implicit in the
# socket-service relationship, see systemd.socket(5).
# Note that notify will only work if --daemonize=no
-------------------------------------------------------------------------------

Launch `pulseaudio.socket`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl --user start pulseaudio.socket
-------------------------------------------------------------------------------

Launch `pulseaudio.service`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl --user start pulseaudio.service
-------------------------------------------------------------------------------

Verify if everything is ok.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl --user status pulseaudio.service
● pulseaudio.service - Sound Service
     Loaded: loaded (/usr/lib/systemd/user/pulseaudio.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2024-02-02 22:39:50 CET; 12h ago
TriggeredBy: ● pulseaudio.socket
   Main PID: 9275 (pulseaudio)
      Tasks: 4 (limit: 38100)
     Memory: 5.4M
        CPU: 349ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pulseaudio.service
             └─9275 /usr/bin/pulseaudio --daemonize=no --log-target=journal

lut 02 22:39:49 intellias systemd[2719]: Starting Sound Service...
lut 02 22:39:50 intellias systemd[2719]: Started Sound Service.
-------------------------------------------------------------------------------

Be aware, that the `systemctl` command invoked with `--user` switch is *not*
equivalent to the `systemctl` command invoked without it.

== Configure Proxmox Virtual Environment to use dynamic IP

By default Proxmox Virtual Environment is using static IP configuration. IP
address is configured during installation process. The DHCP for servers is not
recommended, however it is possible to use it.

Install additional DHCP client. Without it network does not work any more.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ apt install isc-dhcp-client
-------------------------------------------------------------------------------

Configuration is done via file `/etc/network/interfaces`. Modify file like
presented below.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /etc/network/interfaces
[...]
auto vmbr0
iface vmbr0 inet dhcp
        bridge-ports ens3
        bridge-stp off
        bridge-fd 0
        bridge-vlan-aware yes
[...]
-------------------------------------------------------------------------------

This configuration changes static IP to dynamic IP, assigned by DHCP server
working in the local network. You have to issue the `ifreload -a` command in
order to take the effect.

When the IP of the Proxmox VE got changed, you have to edit it in the
`/etc/hosts` file as well. You can use automated mathod for that using script
presented below.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /root/update-etc-hosts.sh 
#!/bin/bash

HOSTS_FILE=/etc/hosts
HOSTNAME=$(hostname -f)
IFACE_NAME=vmbr0
OLD_IP_ADDR=$(grep ${HOSTNAME} ${HOSTS_FILE} | xargs | cut -d \  -f 1)
NEW_IP_ADDR=$(ip -4 addr show dev ${IFACE_NAME} | grep -o -E "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/" | tr -d \/)

sed s/"${OLD_IP_ADDR}"/${NEW_IP_ADDR}/g -i ${HOSTS_FILE}
-------------------------------------------------------------------------------

There is no need to assign execute persmissions, because it can be launched by
`systemd`. Create file in `/etc/systemd/system/update-etc-hosts.service` like
presented below.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /etc/systemd/system/update-etc-hosts.service 
[Unit]
DefaultDependencies=no
After=network-online.target
#Before=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh /root/update-etc-hosts.sh

[Install]
WantedBy=network-online.target
-------------------------------------------------------------------------------

Enable service `update-etc-hosts.service`. It will apply changes to
`/etc/hosts` file on every boot.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl enable update-etc-hosts.service
-------------------------------------------------------------------------------

It is also useful to modify `/usr/bin/pvebanner` script to show proper IP
address (fresh one, up to date one) on every login to physical console.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /usr/bin/pvebanner
#!/bin/bash

IFACE_NAME=vmbr0
LOCAL_IP=$(ip -4 addr show dev ${IFACE_NAME} | grep -o -E "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\/" | tr -d \/)

echo ------------------------------------------------------------------------------
echo
echo Welcome to the Proxmox Virtual Environment. Please use your web browser to
echo configure this server - connect to:
echo
echo  https://${LOCAL_IP}:8006/
echo
echo ------------------------------------------------------------------------------
-------------------------------------------------------------------------------

This script will give output the same like original one.

[subs="+attributes"]
-------------------------------------------------------------------------------

Welcome to the Proxmox Virtual Environment. Please use your web browser to
configure this server - connect to:

https://192.168.4.5:8006/

-------------------------------------------------------------------------------

== Poweroff platform every week

Simple systemd timer script `/etc/systemd/system/systemd-poweroff.timer` can
be added for regular poweroff of platform.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /etc/systemd/system/systemd-poweroff.timer
[Unit]
Description=Poweroff every week

[Timer]
OnCalendar=Sun *-*-* 23:00:00

[Install]
WantedBy=timers.target
-------------------------------------------------------------------------------

Enable `systemd-poweroff.timer`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl enable systemd-poweroff.timer
Created symlink '/etc/systemd/system/timers.target.wants/systemd-poweroff.timer' → '/etc/systemd/system/systemd-poweroff.timer'.
-------------------------------------------------------------------------------

Start `systemd-poweroff.timer`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ systemctl enable systemd-poweroff.timer
-------------------------------------------------------------------------------

== Wake-on-LAN

Add new `udev` rule in `/etc/udev/rules.d/81-wol.rules`.

[subs="+attributes"]
-------------------------------------------------------------------------------
[{local_user}@{local_hostname} ~]$ cat /etc/udev/rules.d/81-wol.rules
ACTION=="add", SUBSYSTEM=="net", NAME=="enp*", RUN+="/usr/sbin/ethtool -s $name wol g"
-------------------------------------------------------------------------------

Reboot system.

== Source of information

* https://pve.proxmox.com/wiki/PCI_Passthrough[Proxmox PCI Passthrough]
* https://wiki.archlinux.org/title/PCI_passthrough_via_OVMF[PCI passthrough via OVMF]
* https://www.reddit.com/r/homelab/comments/b5xpua/the_ultimate_beginners_guide_to_gpu_passthrough[The Ultimate Beginner's Guide to GPU Passthrough]
* https://www.reddit.com/r/Proxmox/comments/lcnn5w/proxmox_pcie_passthrough_in_2_minutes[Proxmox PCI(e) Passthrough in 2 minutes]
* https://elijahliedtke.medium.com/home-lab-guides-proxmox-6-pci-e-passthrough-with-nvidia-43ccfb9424de[Home Lab Guides: Proxmox 6 — PCI(e) Passthrough with NVIDIA]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Running[Running the PulseAudio]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Network[Network Setup  of the PulseAudio]
* https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/ServerStrings[The Format of Server Strings in the PulseAudio]
* https://wiki.archlinux.org/title/PulseAudio/Examples#Set_default_input_source[Examples of PulseAudio usage]
* https://wiki.archlinux.org/title/PulseAudio#Configuration_command[PulseAudio environment variables]
* https://gist.github.com/xarinatan/c415341ff34eab445cfb073988dcf6c1[How to set up PulseAudio over Network]]
