name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: latest
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          go get .
      - name: Perform tests
        run: go test -v ./...
